---
name: Spark CI

on: push

jobs:
  sbt:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache build
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.m2/repository
            target
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven

      - uses: vemonet/setup-spark@v1
        with:
          spark-version: 3.3.2
          hadoop-version: 3

      - run: spark-submit --version

      - name: Download dataset
        run: |
          wget https://github.com/datablist/sample-csv-files/raw/main/files/organizations/organizations-100000.csv
          wget https://github.com/datablist/sample-csv-files/raw/main/files/organizations/organizations-500000.zip
          7za x organizations-500000.zip
          wget https://github.com/datablist/sample-csv-files/raw/main/files/organizations/organizations-1000000.zip
          7za x organizations-1000000.zip
          wget https://github.com/datablist/sample-csv-files/raw/main/files/organizations/organizations-2000000.zip
          7za x organizations-2000000.zip

      - name: Assembly it and run it
        run: |
          mvn package
          spark-submit --class "CloudproofSpark" --master "local[*]" target/cloudproof_spark-1.0.0.jar

      - run: cat /proc/cpuinfo

      - name: Benches
        run: |
          sbt "test:testOnly -- -oD"
          du -bch -d 0 out.parquet.*

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Maven deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
          mkdir -p ~/.m2 ~/.gpg
          echo "$M2_SETTINGS" > ~/.m2/settings.xml
          echo "$MAVEN_GPG_PRIVATE_KEY" > ~/.gpg/maven_gpg_private_key.asc
          mvn clean deploy -Dmaven.test.skip
        env:
          M2_SETTINGS: ${{ secrets.M2_SETTINGS }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

  release:
    needs:
      - sbt
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1

  cleanup:
    needs:
      - release
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    secrets: inherit
